package net.nikdo53.neobackports.datamaps;

import com.mojang.serialization.Codec;
import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Fabric reimplementation of NeoBackports/NeoForge's {@code DataMapType} — see
 * FABRIC_PORT_PLAN.md §5.6. Real NeoForge data maps patch vanilla's {@code Holder<T>} class
 * itself to add {@code Holder.getData(DataMapType)} — the same javac-vs-Mixin-timing
 * impossibility as §5.2's {@code ItemStack} components and §5.5's {@code Entity} attachments,
 * so lookups go through the {@link com.wdiscute.starcatcher.registry.SCDataMaps} static facade
 * instead of an instance method.
 * <p>
 * Deliberately reimplemented from scratch rather than vendoring the unpublished, unreleased,
 * READMEless "Datamaps Refabricated" (0 stars, 8 commits, no Maven coordinate — would need
 * cloning + building an entire unfamiliar Fabric Loom project from source) — the real value of
 * data maps for this mod is small and well-understood (5 maps, JSON already generated by the
 * existing datagen provider), and the vendored library would have hit the exact same
 * Holder-instance-method wall anyway, needing a flatten regardless.
 */
public class DataMapType<R, T>
{
    private final ResourceLocation id;
    private final ResourceKey<? extends Registry<R>> registryKey;
    private final Codec<T> codec;
    private final Map<ResourceLocation, T> values = new ConcurrentHashMap<>();

    private DataMapType(ResourceLocation id, ResourceKey<? extends Registry<R>> registryKey, Codec<T> codec)
    {
        this.id = id;
        this.registryKey = registryKey;
        this.codec = codec;
    }

    public ResourceLocation id()
    {
        return id;
    }

    public ResourceKey<? extends Registry<R>> registryKey()
    {
        return registryKey;
    }

    public Codec<T> codec()
    {
        return codec;
    }

    public T get(ResourceLocation entryId)
    {
        return values.get(entryId);
    }

    void reload(Map<ResourceLocation, T> newValues)
    {
        values.clear();
        values.putAll(newValues);
    }

    public static <R, T> Builder<R, T> builder(ResourceLocation id, ResourceKey<? extends Registry<R>> registryKey, Codec<T> codec)
    {
        return new Builder<>(id, registryKey, codec);
    }

    public static class Builder<R, T>
    {
        private final ResourceLocation id;
        private final ResourceKey<? extends Registry<R>> registryKey;
        private final Codec<T> codec;

        private Builder(ResourceLocation id, ResourceKey<? extends Registry<R>> registryKey, Codec<T> codec)
        {
            this.id = id;
            this.registryKey = registryKey;
            this.codec = codec;
        }

        /**
         * Kept for source-compatibility with the original NeoForge-style builder chain, but a
         * no-op here: this reimplementation always loads from (integrated/dedicated) server data
         * packs, with no separate network codec — the original's {@code synced} flag existed to
         * push resolved values to remote multiplayer clients over the network, which is a real,
         * intentionally deferred gap of this reimplementation (see FABRIC_PORT_PLAN.md §5.6);
         * singleplayer/integrated-server play (the overwhelming common case) is unaffected since
         * client and server share the same data packs there.
         */
        public Builder<R, T> synced(Codec<T> networkCodec, boolean required)
        {
            return this;
        }

        public DataMapType<R, T> build()
        {
            DataMapType<R, T> type = new DataMapType<>(id, registryKey, codec);
            DataMapRegistry.register(type);
            return type;
        }
    }
}
